name: smart_cooking_ai
description: Smart Cooking AI - Hệ thống nấu ăn thông minh với AI và Voice Assistant

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI/UX Dependencies
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  lottie: ^3.1.2

  # State Management
  provider: ^6.1.2
  get: ^4.6.6

  # Internationalization (i18n)
  easy_localization: ^3.0.7
  intl: ^0.20.2

  # Networking & API
  http: ^1.2.2
  dio: ^5.7.0
  connectivity_plus: ^6.0.5

  # Local Storage
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Authentication
  google_sign_in: ^6.2.1
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  flutter_appauth: ^6.0.7
  flutter_secure_storage: ^9.2.2

  # Voice & AI Features (comment out for now)
  # speech_to_text: ^7.0.0
  # flutter_tts: ^4.1.0

  # Location & Maps
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  google_maps_flutter: ^2.9.0
  location: ^7.0.0

  # Image & Camera
  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  permission_handler: ^11.3.1

  # Utils
  path_provider: ^2.1.4
  url_launcher: ^6.3.1
  package_info_plus: ^8.0.2
  device_info_plus: ^10.1.2
  go_router: ^16.0.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/translations/

  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
